'use strict';

const fs = require('fs');
const path = require('path');
const catalog = require('../src/data/craftingCatalog');

const escapeCell = value => String(value ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');
const ingredientText = recipe => recipe.ingredients.map(input => {
    const definition = catalog.MATERIAL_BY_ID[input.itemId] || catalog.CRAFTABLE_BY_ID[input.itemId];
    return `${input.quantity} ${definition ? definition.name : input.itemId}`;
}).join('<br>');

const lines = [
    '# Bconomy v3.0.0 Crafting Catalog',
    '',
    '> Generated from the canonical runtime catalog with `npm run docs:crafting`. Do not edit this file by hand.',
    '',
    `- Raw materials: ${catalog.VALIDATION_SUMMARY.materialCount}`,
    `- New craftables: ${catalog.VALIDATION_SUMMARY.newCraftableCount}`,
    `- Legacy components: ${catalog.VALIDATION_SUMMARY.legacyCraftableCount}`,
    `- Socket modules: ${catalog.VALIDATION_SUMMARY.socketModuleCount}`,
    `- Total recipes: ${catalog.VALIDATION_SUMMARY.recipeCount}`,
    '',
    '## Acquisition quotas',
    '',
    '| Action | Material types |',
    '| --- | ---: |',
    ...Object.entries(catalog.VALIDATION_SUMMARY.sourceCounts).map(([action, count]) => `| ${action} | ${count} |`),
    ''
];

for (const domain of catalog.DOMAIN_ORDER) {
    lines.push(`## ${catalog.DOMAIN_NAMES[domain]}`, '', '### Raw materials', '');
    lines.push('| ID | Name | Rarity | Source | Unit | Description |', '| --- | --- | --- | --- | --- | --- |');
    for (const item of catalog.MATERIALS.filter(candidate => candidate.domain === domain)) {
        lines.push(`| ${escapeCell(item.id)} | ${escapeCell(item.name)} | ${escapeCell(item.rarity)} | ${escapeCell(item.sourceAction)} | ${escapeCell(item.unit.id)} | ${escapeCell(item.description)} |`);
    }
    lines.push('', '### Craftable products', '');
    lines.push('| ID | Name | Type | Effort | Form | Output | Bill of materials | Description |', '| --- | --- | --- | --- | --- | --- | --- | --- |');
    for (const item of catalog.NEW_CRAFTABLES.filter(candidate => candidate.domain === domain)) {
        const recipe = catalog.RECIPE_BY_ID[item.recipeId];
        lines.push(`| ${escapeCell(item.id)} | ${escapeCell(item.name)} | ${escapeCell(item.classification)} | ${escapeCell(item.effortBand)} | ${catalog.recipeForm(recipe)} | ${recipe.output.quantity} ${escapeCell(item.unit.singular)} | ${ingredientText(recipe)} | ${escapeCell(item.description)} |`);
    }
    lines.push('');
}

lines.push('## Integrated existing craftables', '', '| ID | Name | Type | Storage | Bill of materials |', '| --- | --- | --- | --- | --- |');
for (const item of [...catalog.LEGACY_CRAFTABLES, ...catalog.MODULE_CRAFTABLES]) {
    lines.push(`| ${escapeCell(item.id)} | ${escapeCell(item.name)} | ${escapeCell(item.classification)} | ${escapeCell(item.storage)} | ${ingredientText(catalog.RECIPE_BY_ID[item.recipeId])} |`);
}

fs.writeFileSync(path.join(__dirname, '..', 'docs', 'crafting-catalog.md'), `${lines.join('\n')}\n`, 'utf8');
